### ISSUE TITLE
ROS biotac edge,corner,surface

### ISSUE THREAD

**Issue by SabrinaFrohn** [CNCR-NTU/biotac_sp_sensors#1]
These are all existing Files. 

[trial_ws.zip](https://github.com/CNCR-NTU/biotac_sp_sensors/files/2266696/trial_ws.zip)

Current output when running: 
```
$ cat ~/.bashrc | tail
_if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

#export USB_DEVFS_PATH="/sys/bus/usb/devices/"
source /opt/ros/melodic/setup.bash_
```

**Comment by pedrombmachado** [comment]
@SabrinaFrohn ,
  Please edit your .bashrc and remove the two last lines:
```
$ nano ~/.bashrc
```
add the following lines:

> echo "ROS Melodic environment"
> source "/opt/ros/melodic/setup.bash"
> source "$HOME/catkin_ws/devel/setup.bash"

after that:
```
$ source ~/.bashrc
```
Now unzip the content of the zipped file to ~/catkin_ws/src and build the packet
```
$ unzip trial_ws.zip ~/catkin_ws/src
$ cd ~/catkin_ws
$ catkin_make
```
Please provide the all the output if an error is generated.

**Comment by SabrinaFrohn** [comment]
I did as you wrote and everything worked fine. 
Then I wanted to run the code but this happened: 

~/catkin_ws/src/RosML$ ./main.ccp
bash: ./main.ccp: No such file or directory
:~/catkin_ws/src/RosML$ ls
include  __init__.py  __init__.pyc  main.cpp  src

**Comment by pedrombmachado** [comment]
@SabrinaFrohn 
what do you have inside of the bin folder? There should be a new executable. Can you show me what do you have inside of the manifest.xml
however if you jaust want the the gui open the file named /trial_ws/src/ui/ml_window.ui

**Comment by pedrombmachado** [comment]
@SabrinaFrohn ,
  I found this [tutorial](https://www.learnopencv.com/cvui-gui-lib-built-on-top-of-opencv-drawing-primitives/) that can be very useful for you to create the UI that you want.

**Comment by pedrombmachado** [comment]
@SabrinaFrohn ,
  It is probably easier to write your own GUI because it will take more time to understand what is happening. Please find bellow some suggestions to help you do what you want:
[link1](https://www.learnopencv.com/blob-detection-using-opencv-python-c/)
[link2](https://www.learnopencv.com/head-pose-estimation-using-opencv-and-dlib/)
[link3](https://www.learnopencv.com/blob-detection-using-opencv-python-c/)
The reason why I am suggestion openCV is because an image is 2D matrix where each pixels has some degree of correlation with the neighbour pixels and the same concept can applied to a haptic sensor.
I hope it helps.

**Comment by SabrinaFrohn** [comment]
@pedrombmachado 
Thanks I will look into that. 
But I'm actually trying to do two different things. 
1: make my own gui for the pressure representation
2: run guillaumes' code
Or are you suggesting that I'll write my own gui for guillaumes' code as well?

**Comment by pedrombmachado** [comment]
I think it will take you less time to write your own gui.
